### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by BlinkyR** [ds4owd-001/md-02-assignments-BlinkyR#1]
Hello @larnsce @mianzg @sskorik01,

I just wanted to inform you that I completed the module 2 assignment.

I have two questions though:
1) If I don't change #| eval:  from false to true, does it make the code chunk inactive? I tried to google it but [the #| eval function is not valid syntax]( https://www.perplexity.ai/search/715c6b76-ebfb-46d7-9fd3-5f3901ed472f?s=u).
2) Secondly, Can you send me an invite to use Element my Github username is BlinkyR and my email is brucerutayisire@gmail.com. Whenever I try to create an account with those accounts I can't find the openwashdata group.

Thanks,
Bruce.

**Comment by larnsce** [comment]
Hi @BlinkyR, you haven't committed and pushed your code (your code in md-02a-data-visualization.qmd has not been updated on GitHub). You need to commit and push from posit.cloud to confirm you have finished your assignment.

Your questions:

1. Yes, when you "Render" it does not eval(uate) the code chunk were the option is set to `false`. I do this, because otherwise I could not keep placeholders. The code with placeholders would throw an error on "Render". 

2. Element

The invite link should be the one that's published on our homepage: https://matrix.to/#/#openwashdata-lobby:staffchat.ethz.ch. At which step does it not work for you: https://ds4owd-001.github.io/website/assignments/md-01/am-01-2-element.html

**Comment by BlinkyR** [comment]
It is done now. I forgot to push. 

and thanks for the Element app, it is now working.

**Comment by larnsce** [comment]
Great, I will close the issue for you now.
